adapter: lora
base_model: --BASE_MODEL--
bf16: auto
dataset_processes: 4

datasets:
  - path: --DATASET_REPO_ID--       # Training dataset
    type: chat_template
    chat_template: llama-3-instruct
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant: [assistant]
      user: [user]
    roles_to_train: ["assistant"]
    train_on_eos: "turn"

  - path: --VAL_DATASET_PATH--        # Validation dataset
    type: chat_template
    chat_template: llama-3-instruct
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant: [assistant]
      user: [user]
    roles_to_train: ["assistant"]
    is_validation: true

special_tokens:
  eos_token: "</s>"
  bos_token: "<s>"
  pad_token: "<s>"

gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 0.0002

load_in_4bit: true
load_in_8bit: false
bnb_4bit_compute_dtype: float16
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: nf4

lora_alpha: 128
lora_dropout: 0.05
lora_r: 64

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

lora_modules_to_save:
  - embed_tokens
  - lm_head

resize_tokenizer_embeddings_to_match: true
loraplus_lr_embedding: 1.0e-06
lr_scheduler: cosine
max_prompt_len: 8192
mean_resizing_embeddings: false

micro_batch_size: 2
num_epochs: 3.0
optimizer: adamw_bnb_8bit
output_dir: --OUTPUT_DIR--

qlora_sharded_model_loading: false
ray_num_workers: 1
resources_per_worker:
  GPU: 1

save_only_model: false
save_safetensors: true
sequence_len: 8192
shuffle_merged_datasets: true
skip_prepare_dataset: false
strict: false
train_on_inputs: false

trl:
  log_completions: false
  use_vllm: false

use_ray: false
val_set_size: 0.01
weight_decay: 0.0

flash_attention: true