adapter: lora
base_model: --BASE_MODEL--
bf16: auto
dataset_processes: 4

datasets:
  - path: --DATASET_REPO_ID--
    type: chat_template
    chat_template: chatml
    field_messages: messages
    message_property_mappings:
      role: role
      content: content
    roles:
      assistant:
        - assistant
      user:
        - user
    roles_to_train: ["assistant"]
    train_on_eos: "turn"

special_tokens:
  eos_token: "<|im_end|>"
  bos_token: "<|im_start|>"
  pad_token: "<|im_end|>"

gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 0.0002

load_in_4bit: true
load_in_8bit: false
bnb_4bit_compute_dtype: float16
bnb_4bit_use_double_quant: true
bnb_4bit_quant_type: nf4

lora_alpha: 32  # Increased for better style capture
lora_dropout: 0.05
lora_r: 16      # Increased for better style capture

lora_target_modules:
  - Wqkv        # Combined QKV layer
  - out_proj    # Output projection
  - fc1         # Feedforward layer 1
  - fc2         # Feedforward layer 2

lora_modules_to_save:
  - embed_tokens
  - lm_head

resize_tokenizer_embeddings_to_match: true
loraplus_lr_embedding: 1.0e-06
lr_scheduler: cosine
max_prompt_len: 4096
mean_resizing_embeddings: false

micro_batch_size: 1
num_epochs: 5.0  # Increased epochs for small dataset
optimizer: adamw_bnb_8bit
output_dir: --OUTPUT_DIR--

pretrain_multipack_attn: false
pretrain_multipack_buffer_size: 10000

qlora_sharded_model_loading: false
ray_num_workers: 1
resources_per_worker:
  GPU: 1

sample_packing_bin_size: 200
sample_packing_group_size: 100000

save_only_model: false
save_safetensors: true
sequence_len: 4096 # Increase from 2048 to handle longer conversations

shuffle_merged_datasets: true
skip_prepare_dataset: false
strict: false
train_on_inputs: false

trl:
  log_completions: false
  ref_model_mixup_alpha: 0.9
  ref_model_sync_steps: 64
  sync_ref_model: false
  use_vllm: false
  vllm_device: auto
  vllm_dtype: auto
  vllm_gpu_memory_utilization: 0.9

use_ray: false
val_set_size: 0.01
weight_decay: 0.0

flash_attention: true